# Experiment setup
experiment:
  num_seeds: 3
  num_envs: 4
  num_test_envs: 2
  envs:
    Reacher:
      env_id: "Reacher-v5"
      total_timesteps: 200000
    Swimmer:
      env_id: "Swimmer-v5"
      total_timesteps: 1000000
    Hopper:
      env_id: "Hopper-v5"
      total_timesteps: 2500000
logging:
  project: "sparse-ppo-drl-research"
  dormant_threshold: 0.1

phase_0:
  exp:
    num_seeds: 1
    num_envs: 4
  envs:
    env_list: ["Reacher", "Hopper"]
    Reacher:
      env_id: "Reacher-v5"
      total_timesteps: 200000
    Hopper:
      env_id: "Hopper-v5"
      total_timesteps: 2500000
  sparsity:
    dense_allocation: [0.15, 0.10, 0.05, 0.01]
