env_type: 'myosuite'
env_name: ${env_name}
seed: ${seed}

num_env_steps: 1_000_000
episodic: false

num_train_envs: 1
num_eval_envs: 1

no_termination: false
action_repeat: 1
rescale_action: true
reward_scale: 1
max_episode_steps: 1000