# Experiment setup
experiment:
  num_seeds: 5
  num_envs: 1

environments:
  Reacher:
    env_id: "Reacher-v5"
    total_timesteps: 1500000

  Swimmer:
    env_id: "Swimmer-v5"
    total_timesteps: 1000000

  Hopper:
    env_id: "Hopper-v5"
    total_timesteps: 3000000

dst:
  prune_interval: 1
  actor_sparsity_ratio: 0.8
  actor_epsilon: 0.00000001
  regrow_ratio: 0.1

logging:
  project: "sparse-ppo-drl-research" 
  dormant_threshold: 0.1